language: python
python:
  - "2.7"

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq libdb-dev

install:
  - pip install pep8
  - python setup.py install

before_script:
  - pep8 ga4gh tests

script: nosetests
