language: python
python:
  - "2.7"

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq libdb-dev

install:
  - pip install -r requirements.txt
  - python setup.py install

before_script:
  # the following two lines are to prevent travis from
  # verbosely complaining about a security problem; see issue 54
  - mkdir $HOME/.python-eggs
  - chmod og-w $HOME/.python-eggs

script: 
  - flake8 tests ga4gh scripts
  - nosetests --with-coverage --cover-package ga4gh
              --cover-inclusive --cover-min-percentage 80
